In [1]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

2.3.1


In [11]:
tf.random.set_seed(0)  # for reproducibility

In [13]:
x1_data = [1, 0, 3, 0, 5]
x2_data = [0, 2, 0, 4, 0]
y_data = [1, 2, 3, 4, 5]

W1 = tf.Variable(tf.random.uniform((1,), -10.0, 10.0))
W2 = tf.Variable(tf.random.uniform((1,), -10.0, 10.0))
b  = tf.Variable(tf.random.uniform((1,), -10.0, 10.0))

learning_rate = tf.Variable(0.001)

for i in range(1000+1):
    with tf.GradientTape() as tape:
        hypothesis = W1 * x1_data + W2 * x2_data + b
        cost = tf.reduce_mean(tf.square(hypothesis - y_data))
    W1_grad, W2_grad, b_grad = tape.gradient(cost, [W1, W2, b])
    W1.assign_sub(learning_rate * W1_grad)
    W2.assign_sub(learning_rate * W2_grad)
    b.assign_sub(learning_rate * b_grad)
    
    if i % 50 == 0:
        print("{:5} | {:10.6f} | {:10.4f} | {:10.4f} | {:10.6f}".format(
        i, cost.numpy(), W1.numpy()[0], W2.numpy()[0], b.numpy()[0]))

    0 | 966.489624 |    -6.3849 |    -9.6386 |  -1.997182
   50 | 290.719482 |    -2.5520 |    -6.0406 |   0.083186
  100 |  97.416336 |    -0.8520 |    -3.7830 |   1.185548
  150 |  36.060600 |    -0.1155 |    -2.3524 |   1.777458
  200 |  14.622516 |     0.1927 |    -1.4381 |   2.096439
  250 |   6.551729 |     0.3151 |    -0.8494 |   2.265759
  300 |   3.350713 |     0.3601 |    -0.4675 |   2.350938
  350 |   2.032307 |     0.3750 |    -0.2176 |   2.387711
  400 |   1.469417 |     0.3797 |    -0.0524 |   2.396086
  450 |   1.216593 |     0.3823 |     0.0583 |   2.387553
  500 |   1.092846 |     0.3854 |     0.1338 |   2.368865
  550 |   1.023482 |     0.3899 |     0.1865 |   2.344070
  600 |   0.977404 |     0.3956 |     0.2244 |   2.315640
  650 |   0.941599 |     0.4023 |     0.2527 |   2.285101
  700 |   0.910600 |     0.4097 |     0.2748 |   2.253407
  750 |   0.882098 |     0.4175 |     0.2927 |   2.221159
  800 |   0.855110 |     0.4255 |     0.3080 |   2.188733
  850 |   0.82

In [15]:
x_data = [
    [1., 1., 1., 1., 1.,],
    [1., 0., 3., 0., 5.,],
    [0., 2., 0., 4., 0.,]
]

y_data = [1,2,3,4,5]

W = tf.Variable(tf.random.uniform((1,3), -1.0, 1.0))

learning_rate = 0.001
optimizer = tf.keras.optimizers.SGD(learning_rate)

for i in range(1000+1):
    with tf.GradientTape() as tape:
        hypothesis = tf.matmul(W, x_data)
        cost = tf.reduce_mean(tf.square(hypothesis - y_data))
    
    grads = tape.gradient(cost, [W])
    optimizer.apply_gradients(grads_and_vars=zip(grads,[W]))
    if i% 50 == 0:
        print("{:5} | {:10.6f} | {:10.4f} | {:10.4f} | {:10.4f}".format(
            i, cost.numpy(), W.numpy()[0][0], W.numpy()[0][1], W.numpy()[0][2]))

    0 |  24.553152 |    -0.8860 |    -0.5956 |     0.9471
   50 |   5.404427 |    -0.6144 |     0.3053 |     1.0368
  100 |   1.204501 |    -0.4842 |     0.7263 |     1.0780
  150 |   0.282872 |    -0.4201 |     0.9227 |     1.0966
  200 |   0.080195 |    -0.3872 |     1.0139 |     1.1045
  250 |   0.035202 |    -0.3689 |     1.0558 |     1.1073
  300 |   0.024805 |    -0.3575 |     1.0747 |     1.1078
  350 |   0.022011 |    -0.3493 |     1.0828 |     1.1072
  400 |   0.020901 |    -0.3427 |     1.0859 |     1.1060
  450 |   0.020174 |    -0.3369 |     1.0866 |     1.1047
  500 |   0.019546 |    -0.3315 |     1.0862 |     1.1032
  550 |   0.018954 |    -0.3264 |     1.0854 |     1.1017
  600 |   0.018383 |    -0.3214 |     1.0843 |     1.1002
  650 |   0.017830 |    -0.3165 |     1.0831 |     1.0987
  700 |   0.017295 |    -0.3117 |     1.0819 |     1.0972
  750 |   0.016775 |    -0.3070 |     1.0807 |     1.0957
  800 |   0.016271 |    -0.3023 |     1.0795 |     1.0943
  850 |   0.01

In [23]:
X = tf.constant([[1., 2.], 
                 [3., 4.]])
y = tf.constant([[1.5], [3.5]])

W = tf.Variable(tf.random.normal((2, 1)))
b = tf.Variable(tf.random.normal((1,)))

# Create an optimizer
optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)

n_epoch = 1000+1
print("epoch | cost")
for i in range(n_epoch):
    with tf.GradientTape() as tape:
        y_pred = tf.matmul(X, W) + b
        cost = tf.reduce_mean(tf.square(y_pred - y))
    
    grads = tape.gradient(cost, [W, b])
    
    optimizer.apply_gradients(grads_and_vars=zip(grads, [W, b]))
    if i% 50 == 0:
        print("{:5} | {:10.6f}".format(i, cost.numpy()))

epoch | cost
    0 |   3.664075
   50 |   0.210658
  100 |   0.144028
  150 |   0.098474
  200 |   0.067327
  250 |   0.046032
  300 |   0.031473
  350 |   0.021518
  400 |   0.014712
  450 |   0.010059
  500 |   0.006877
  550 |   0.004702
  600 |   0.003215
  650 |   0.002198
  700 |   0.001503
  750 |   0.001027
  800 |   0.000703
  850 |   0.000480
  900 |   0.000328
  950 |   0.000225
 1000 |   0.000154


In [24]:
tf.random.set_seed(0)

In [27]:
# data and label
x1 = [ 73.,  93.,  89.,  96.,  73.]
x2 = [ 80.,  88.,  91.,  98.,  66.]
x3 = [ 75.,  93.,  90., 100.,  70.]
Y  = [152., 185., 180., 196., 142.]

# weights
w1 = tf.Variable(10.)
w2 = tf.Variable(10.)
w3 = tf.Variable(10.)
b  = tf.Variable(10.)

learning_rate = 0.000001

for i in range(1000+1):
    # tf.GradientTape() to record the gradient of the cost function
    with tf.GradientTape() as tape:
        hypothesis = w1 * x1 +  w2 * x2 + w3 * x3 + b
        cost = tf.reduce_mean(tf.square(hypothesis - Y))
    # calculates the gradients of the cost
    w1_grad, w2_grad, w3_grad, b_grad = tape.gradient(cost, [w1, w2, w3, b])
    
    # update w1,w2,w3 and b
    w1.assign_sub(learning_rate * w1_grad)
    w2.assign_sub(learning_rate * w2_grad)
    w3.assign_sub(learning_rate * w3_grad)
    b.assign_sub(learning_rate * b_grad)

    if i % 50 == 0:
      print("{:5} | {:12.4f}".format(i, cost.numpy()))

    0 | 5793889.5000
   50 |   64291.1562
  100 |     715.2903
  150 |       9.8461
  200 |       2.0152
  250 |       1.9252
  300 |       1.9210
  350 |       1.9177
  400 |       1.9145
  450 |       1.9114
  500 |       1.9081
  550 |       1.9050
  600 |       1.9018
  650 |       1.8986
  700 |       1.8955
  750 |       1.8923
  800 |       1.8892
  850 |       1.8861
  900 |       1.8829
  950 |       1.8798
 1000 |       1.8767


In [28]:
# data and label
x1 = [ 73.,  93.,  89.,  96.,  73.]
x2 = [ 80.,  88.,  91.,  98.,  66.]
x3 = [ 75.,  93.,  90., 100.,  70.]
Y  = [152., 185., 180., 196., 142.]

# random weights
w1 = tf.Variable(tf.random.normal((1,)))
w2 = tf.Variable(tf.random.normal((1,)))
w3 = tf.Variable(tf.random.normal((1,)))
b  = tf.Variable(tf.random.normal((1,)))

learning_rate = 0.000001

for i in range(1000+1):
    # tf.GradientTape() to record the gradient of the cost function
    with tf.GradientTape() as tape:
        hypothesis = w1 * x1 +  w2 * x2 + w3 * x3 + b
        cost = tf.reduce_mean(tf.square(hypothesis - Y))
    # calculates the gradients of the cost
    w1_grad, w2_grad, w3_grad, b_grad = tape.gradient(cost, [w1, w2, w3, b])
    
    # update w1,w2,w3 and b
    w1.assign_sub(learning_rate * w1_grad)
    w2.assign_sub(learning_rate * w2_grad)
    w3.assign_sub(learning_rate * w3_grad)
    b.assign_sub(learning_rate * b_grad)

    if i % 50 == 0:
      print("{:5} | {:12.4f}".format(i, cost.numpy()))

    0 |    3528.1030
   50 |      92.7332
  100 |      54.4777
  150 |      53.9173
  200 |      53.7753
  250 |      53.6384
  300 |      53.5022
  350 |      53.3662
  400 |      53.2305
  450 |      53.0953
  500 |      52.9603
  550 |      52.8258
  600 |      52.6917
  650 |      52.5578
  700 |      52.4243
  750 |      52.2911
  800 |      52.1583
  850 |      52.0259
  900 |      51.8939
  950 |      51.7621
 1000 |      51.6306


In [31]:
data = np.array([
    # X1,   X2,    X3,   y
    [ 73.,  80.,  75., 152. ],
    [ 93.,  88.,  93., 185. ],
    [ 89.,  91.,  90., 180. ],
    [ 96.,  98., 100., 196. ],
    [ 73.,  66.,  70., 142. ]
], dtype=np.float32)

# slice data
X = data[:, :-1]
y = data[:, [-1]]

W = tf.Variable(tf.random.normal((3, 1)))
b = tf.Variable(tf.random.normal((1,)))

learning_rate = 0.000001

def predict(X):
    return tf.matmul(X,W) + b

print("epoch | cost")

n_epochs = 2000
for i in range(n_epochs+1):
    with tf.GradientTape() as tape:
        cost = tf.reduce_mean((tf.square(predict(X) - y)))
    
    W_grad, b_grad = tape.gradient(cost, [W, b])

    # updates parameters (W and b)
    W.assign_sub(learning_rate * W_grad)
    b.assign_sub(learning_rate * b_grad)
    
    if i % 100 == 0:
        print("{:5} | {:10.4f}".format(i, cost.numpy()))

epoch | cost
    0 | 195206.6562
  100 |    40.8115
  200 |    16.6931
  300 |    16.6015
  400 |    16.5132
  500 |    16.4254
  600 |    16.3381
  700 |    16.2514
  800 |    16.1649
  900 |    16.0791
 1000 |    15.9937
 1100 |    15.9088
 1200 |    15.8243
 1300 |    15.7403
 1400 |    15.6566
 1500 |    15.5736
 1600 |    15.4908
 1700 |    15.4087
 1800 |    15.3268
 1900 |    15.2455
 2000 |    15.1645


In [32]:
W.numpy()

array([[0.25667503],
       [1.2582879 ],
       [0.5000149 ]], dtype=float32)

In [33]:
b.numpy()

array([-0.13203251], dtype=float32)

In [34]:
tf.matmul(X, W) + b

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[156.7694 ],
       [180.96947],
       [182.21758],
       [197.82248],
       [136.65329]], dtype=float32)>

In [35]:
Y

[152.0, 185.0, 180.0, 196.0, 142.0]

In [36]:
predict(X).numpy()

array([[156.7694 ],
       [180.96947],
       [182.21758],
       [197.82248],
       [136.65329]], dtype=float32)

In [37]:
predict([[89., 95., 92.],[84., 92., 85.]]).numpy()

array([[188.25078],
       [179.69243]], dtype=float32)